@startuml
package api{
    class OptionEngageApi{
        + engage(UserId userId)
    }
}
package service{

    class PremiumOptionEngageService{
    + void engage(UserId userId)
    }
    class NoticeService{
    + void send(Notification notification)
    }
}
OptionEngageApi .down.> PremiumOptionEngageService
PremiumOptionEngageService .right.> NoticeService
package domain{
package movie{
package movie_register_user{
        class MovieRegisterUserEntity <<Entity>> {
            UserId userId
            RegistrationDate registrationDate
            Option<PremiumOption> premiumOption
            ContactInformation contactInformation
            Option<IntroductionCode> introductionCode

            + Notification createNotification()
        }
        class UserId <<Key>>{
            String value
            + boolean canEngagePremiumOption()
        }
        class RegistrationDate{
            LocalDate value
            + boolean isPastOneYearStartedEngagement()
        }
        class PremiumOption{
            OptionNumber optionNumber
        }
        class OptionNumber{
            String value
        }
        class ContactInformation{

        }
        class SMS {
            PhoneNumber phoneNumber
        }
        class PhoneNumber{
            String value
            + {static} NotificationTo createNotificationTo()
        }
        class Mail {
            MailAddress mailAddress
        }
        class MailAddress{
            String value
            + {static} NotificationTo createNotificationTo()
        }
        interface MovieUserRepository{
        + MovieRegisterUserEntity refer(UserId userId)
        + OptionNumber engagePremiumOption(UserId userId)
        + void send(ContactInformation contactInformation, OptionNumber optionNumber)
        }
        MovieRegisterUserEntity .down.> UserId
        MovieRegisterUserEntity .down.> RegistrationDate
        MovieRegisterUserEntity .down.> PremiumOption
        MovieRegisterUserEntity "1" o-- "0..1" PremiumOption
        MovieRegisterUserEntity .down.> ContactInformation
        ContactInformation .down.> SMS
        ContactInformation "1" o-- "0..1" SMS
        ContactInformation .down.> Mail
        ContactInformation "1" o-- "0..1" Mail
        SMS .down.> PhoneNumber
        Mail .down.> MailAddress
        PremiumOption .down.> OptionNumber
    }
    package introduction_code{
        class IntroductionCode{
            PremiumOptionIntroductionCode premiumOptionIntroductionCode
            IntroductionCodeUseState introductionCodeUseState
        }
        class PremiumOptionIntroductionCode {
            String value
        }
        enum IntroductionCodeUseState{
            USE,
            UNUSED
            + boolean isUnused()
        }
    }
}

    MovieUserRepository .down.> UserId
    MovieUserRepository .down.> MovieRegisterUserEntity
    MovieRegisterUserEntity .down.> IntroductionCode
    MovieRegisterUserEntity "1" o-- "0..1" IntroductionCode
    IntroductionCode .down.> PremiumOptionIntroductionCode
    IntroductionCode .down.> IntroductionCodeUseState
}
PremiumOptionEngageService .down.> MovieUserRepository
NoticeService .down.> MovieUserRepository

@enduml

